### PR TITLE
fix: typo and minor errors

### PR DESCRIPTION
**Pull request by Raj-Pansuriya**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes no issue

### CODE REVIEW

**Review by gikf — APPROVED** [review]
Looks good to me :+1:

**Comment by gikf** [comment]
:thinking: this should have been closed automatically on merge

**Comment by Raj-Pansuriya** [comment]
I don't get this sir, the changes are merged or not? 😅😅

**Comment by gikf** [comment]
I think they are - https://github.com/freeCodeCamp/learn-bash-and-sql-by-building-a-bike-rental-shop/commits/main - but as it can be seen, there isn't other usual markers, that PR was merged :man_shrugging:

**Pull request closed without merging**
